### PR TITLE
bar chart race (WIP)

### PR DESCRIPTION
**Pull request by yjunechoe**
Thanks for a great package! I've been playing around with your package and made a quick draft of an animated bar chart race. Not thoroughly tested but I adopted the relevant `options` that you also have in other functions.

```
library(ddplot)
library(dplyr)
gapminder::gapminder %>%
  filter(country %in% c("Japan", "Mexico", "Germany", "Brazil", "Mexico", "Philippines", "Vietnam")) %>%
  mutate(pop = pop/1e6) %>%
  barChartRace(
    x = "pop",
    y = "country",
    time = "year",
    ytitle = "Country",
    xtitle = "Population (in millions)",
    title = "Bar chart race of country populations"
  )
```

barchartrace

The time variable needs a `d3.scaleTime` so it can take datetimes, but I haven't worked with time formats before so still working on it. Any thoughts on this (w.r.t. datetime conversion from R -> JS and making a scale for the time variable) would be appreciated!

TODO: 

- [ ] Format time variable with `d3.scaleTime`
- [ ] Fix auto-adjusting of the left-margin to the largest y-label. This needs to account for user-supplied font params over all labels (since default isn't monotype, shorter string can still have longer text)
- [x] (Feature) pluck out a separate `transitionDur` argument from `frameDur` (current `frameDur` is actually duration of transiiton with no pause on the actual frame)
- [x] (Feature) user-supplied [easing method](https://github.com/d3/d3-ease)

### CODE REVIEW

**Comment by yjunechoe** [comment]
And this isn't technically a "race" but using the `data` from the `stackedAreaChart()` example in the [vignette](https://feddelegrand7.github.io/ddplot/articles/Start.html):

```
data
#>          date Trade Manufacturing Leisure Agriculture
#> 1  2000-01-01  2000           734    1782         655
#> 2  2000-02-01  1023           694    1779         587
#> 3  2000-03-01   983           739    1789         623
#> 4  2000-04-01  2793           736     658         517
#> 5  2000-05-01  1821           685     675         561
#> 6  2000-06-01  1837           621     833        2545
#> 7  2000-07-01  1792           708     786         636
#> 8  2000-08-01  1853           685     675         584
#> 9  2000-09-01   791           667     636         559
#> 10 2000-10-01   739           693     691        2504

library(ddplot)
library(dplyr)

data %>%
  tidyr::pivot_longer(-date, names_to = "sector", values_to = "unemployment") %>%
  mutate(month = lubridate::month(date)) %>%
  barChartRace(
    x = "unemployment",
    y = "sector",
    time = "month",
    frameDur = 700,
    colorCategory = "Tableau10",
    xticks = 5,
    xtitle = "Unemployment",
    ytitle = "Sector",
    ytitleFontSize = 18,
    title = "Unemployment by sector in 2000",
    panelcol = "skyblue",
    xgridlinecol = "salmon",
    timeLabelOpts = list(prefix = "Month: ", xOffset = 0.2)
  )
```

barchartrace_ex2

**Comment by feddelegrand7** [comment]
Hi @yjunechoe this is absolutely awesome. Thank you so much. Could you send me your last name, first name and email so that I set you as a contributor in the DESCRIPTION file? 

Thanks again.

**Comment by feddelegrand7** [comment]
@yjunechoe btw for the date variable I ask users to provide a date in yyyy-mm-dd format and then I use d3.scaleUtc but your function is just perfect as it allows users to use the months of a particular year. Pretty cool!!!

**Comment by feddelegrand7** [comment]
Could you please add an example of your graph in the vignette (getting started)? thank you in advance

**Comment by yjunechoe** [comment]
Thanks for the feedback! `d3.scaleUtc` looks like what I was looking for - I'll play around with this to allow more flexible inputs to the time variable and see how it turns out. I'll also add examples to the vignette as well (thanks for the reminder!).

And here's my info (more details on my [website](https://yjunechoe.github.io/) as well if you need):

Name: June Choe
Email: jchoe001@gmail.com

I think (hope?) the current version covers the very basic use-cases, so I think it'd also be worth seeing what people think about it (if you're willing to share it for testing at this stage).

Cheers!

**Comment by feddelegrand7** [comment]
Hi @yjunechoe yes for sure we can share it on Twitter, I would be happy if you could share your contribution as it looks neat!

**Comment by yjunechoe** [comment]
Sounds good! I'm going to PR the two features on the TODO real quick (adding `transitionDur` and `ease` arguments) in addition to the vignette examples, and will share after that's merged!

**Pull request merged**
